#pragma once

#include "NativeGameplayTags.h"

namespace DungeonRealmsGameplayTags
{
	DUNGEONREALMS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Gameplay_AbilityInputBlocked)
	
	DUNGEONREALMS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Action_Move)
	DUNGEONREALMS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Action_Look)

	DUNGEONREALMS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Health_Damaged)
	DUNGEONREALMS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Dead)
};
